# -*- coding: utf-8 -*-
"""1464. Maximum Product of Two Elements in an Array

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_O2jTS98mmGwWxGZ5czYTxeeMQNr0xDn
"""

class Solution:
    def maxProduct(self, a: List[int]) -> int:
        '''
        # Sort array
        a.sort()
        return (a[-1]-1) *(a[-2]-1)'''
        
        '''
        # O(n^2)
        l=[]
        n=len(a)
        for i in range(n):
            for j in range(i+1,n):
                l.append((a[i]-1)*(a[j]-1))
        return max(l)
        
        '''
        
        # O(n)
        
        f,s=0,0
        for i in a:
            if i>f:
                f,s=i,f
            else:
                s=max(s,i)
        return (f-1)*(s-1)