# -*- coding: utf-8 -*-
"""1572. Matrix Diagonal Sum

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_O2jTS98mmGwWxGZ5czYTxeeMQNr0xDn
"""

class Solution:
    def diagonalSum(self, a: List[List[int]]) -> int:
        
        '''
        # O(n^2)
        
        m=len(a)
        s=0
        for i in range(m):
            for j in range(m):
                if i==j or i+j==m-1:
                    s+=a[i][j]
        return s
                    
        '''     
        
        # O(n)
        
        
        n=len(a)
        mid=n//2
        s=0
        for i in range(n):
            s+=a[i][i]
            s+=a[n-1-i][i]
        if n%2==1:
            s-=a[mid][mid]
        return s