# -*- coding: utf-8 -*-
"""189. Rotate Array

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_O2jTS98mmGwWxGZ5czYTxeeMQNr0xDn
"""

class Solution:
    def rotate(self, a: List[int], k: int) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        def reverse(a,s,e):
            while s<e:
                a[s],a[e]=a[e],a[s]
                s,e=s+1,e-1
            

        if k==0 or k==None:
            return
        
        n=len(a)
        k=k%n    
        reverse(a,0,n-1)
        reverse(a,0,k-1)
        reverse(a,k,n-1)