# -*- coding: utf-8 -*-
"""1979. Find Greatest Common Divisor of Array

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_O2jTS98mmGwWxGZ5czYTxeeMQNr0xDn
"""

class Solution:
    def findGCD(self, a: List[int]) -> int:
        
        # Euclidean Algorithm
        # TC: O(log(min(a,b)))
        
        s,l=min(a),max(a)
        while s:
            s,l=l%s,s
        return l