# -*- coding: utf-8 -*-
"""26. Remove Duplicates from Sorted Array

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_O2jTS98mmGwWxGZ5czYTxeeMQNr0xDn
"""

class Solution:
    def removeDuplicates(self, a: List[int]) -> int:
        i=0
        j=1
        while j<len(a):
            if a[j]>a[i]:
                a[i+1]=a[j]
                i+=1
            j+=1
        return i+1