# -*- coding: utf-8 -*-
"""283. Move Zeroes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhGB0C1EGQV69ECIawFYczZGHh0w9B0Z
"""

class Solution:
    def moveZeroes(self, a: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        # Two pointers
        
        z=0
        for i in range(len(a)):
            if a[i]!=0:
                a[i],a[z]=a[z],a[i]
                z=z+1